#!/usr/bin/env zsh
# RETIRED 2026-08-16. Read Ornith's per-session token counts out of OpenCode's
# SQLite database; there is no local model any more. issues/ornith-tally.md is
# the closed record it produced.
#
#
# ornith-tally.sh [--markdown]
#
# Tallies what the local model has actually processed, per issue.
#
# The numbers come from OpenCode's own SQLite database, which records
# tokens_input / tokens_output per session — the dispatch logs carry no token
# counts at all, and LM Studio exposes no historical usage endpoint. This is
# the only durable record, and it survives session ends, unlike the
# subagent_tokens figure a dispatcher reports once.
#
# Issue attribution comes from the session's working directory: a dispatch runs
# in ../switchyard-NNNN, so the worktree name is the issue number. Sessions in
# the primary checkout predate the worktree rule and are grouped as "(main)".
#
# --markdown emits just the table.
# --write regenerates issues/ornith-tally.md in full, so the doc cannot go stale.

set -u
setopt ERR_EXIT PIPE_FAIL

DB="$HOME/.local/share/opencode/opencode.db"
[[ -f "$DB" ]] || { print -u2 "ornith-tally: no OpenCode database at $DB"; exit 1 }

MARKDOWN=0
WRITE=0
case "${1:-}" in
  --markdown) MARKDOWN=1 ;;
  --write)    MARKDOWN=1; WRITE=1 ;;
esac

# --write regenerates the doc by re-invoking this script in --markdown mode and
# wrapping the table in prose. Doing it here rather than in a second script
# keeps one source of truth for the query.
if (( WRITE )); then
  DOC="issues/ornith-tally.md"
  {
    print -r -- "# Ornith token tally"
    print -r -- ""
    print -r -- "**Generated by \`./scripts/ornith-tally.sh --write\`. Do not hand-edit — rerun it.**"
    print -r -- ""
    print -r -- "What the local model has actually processed, per issue. Ornith runs in LM Studio on this"
    print -r -- "machine, so the real cost is \$0.00; the hosted column is what the same traffic would have"
    print -r -- "cost on Sonnet 5 at list price (\$3/MTok in, \$15/MTok out), which is the model"
    print -r -- "\`CLAUDE.md\` says it replaces."
    print -r -- ""
    print -r -- "## Where these numbers come from"
    print -r -- ""
    print -r -- "OpenCode's SQLite database, \`~/.local/share/opencode/opencode.db\`, which records"
    print -r -- "\`tokens_input\` and \`tokens_output\` on every session row."
    print -r -- ""
    print -r -- "This matters because **nothing else records it**. The dispatch logs in"
    print -r -- "\`.switchyard-runs/\` carry no token counts, LM Studio exposes no historical usage"
    print -r -- "endpoint, and a dispatcher subagent's \`subagent_tokens\` figure appears once in a"
    print -r -- "notification and is gone when the session ends. The database survives, which is why this"
    print -r -- "file is regenerable rather than a snapshot someone has to remember to update."
    print -r -- ""
    print -r -- "Issues are attributed by the session's working directory: a dispatch runs in"
    print -r -- "\`../switchyard-NNNN\`, so the worktree name is the issue number. That is another reason"
    print -r -- "a dispatch must never run in the primary checkout — it would land in \`(main)\` with no"
    print -r -- "issue attached."
    print -r -- ""
    print -r -- "## The tally"
    print -r -- ""
    "$0" --markdown
    print -r -- ""
    print -r -- "## What the numbers say"
    print -r -- ""
    print -r -- "**Input outweighs output by roughly 100 to 1.** That is the shape of an agentic loop"
    print -r -- "rather than anything about this model: every turn resends the accumulated context, so a"
    print -r -- "long round re-reads its own transcript hundreds of times. It is the strongest argument for"
    print -r -- "running the implementer locally — on a hosted model that ratio *is* the bill."
    print -r -- ""
    print -r -- "**The most expensive rounds are the ones that failed.** #0093 was killed at the timeout"
    print -r -- "having produced nothing usable. #0010 was split for being oversized. #0087 spent three"
    print -r -- "sessions, two of them on a test that asserted nothing. Well over half the total volume"
    print -r -- "went on rounds that were rejected or abandoned."
    print -r -- ""
    print -r -- "That is the cost of authoring defects, and it is invisible in the dollar column precisely"
    print -r -- "because it is free. Free failure is the kind that stops being noticed, which is why"
    print -r -- "\`docs/review-failures.md\` exists and why the preflight refuses a defective issue before"
    print -r -- "a round is spent on it."
    print -r -- ""
    print -r -- "**\`(main)\` covers sessions that predate the worktree rule**, run in the primary"
    print -r -- "checkout — exactly what \`CLAUDE.md\` now forbids."
    print -r -- ""
    print -r -- "## Related"
    print -r -- ""
    print -r -- "- \`issues/cost-ledger.md\` — the hosted side: what authoring and reviewing cost in Opus"
    print -r -- "  tokens, which is the number that is not zero."
    print -r -- "- \`docs/review-failures.md\` — why rounds fail, and the preflight derived from it."
    print -r -- "- \`docs/local-ai-workflow-log.md\` — the running account of this workflow's problems."
  } > "$DOC"
  print "wrote $DOC"
  exit 0
fi

# Hosted comparison. CLAUDE.md says Ornith "replaces Sonnet here", so Sonnet 5
# list pricing is the honest counterfactual: $3/MTok in, $15/MTok out.
IN_RATE=3.0
OUT_RATE=15.0

QUERY="
SELECT
  CASE
    WHEN directory LIKE '%switchyard-%'
      THEN substr(directory, instr(directory, 'switchyard-') + 11, 4)
    ELSE '(main)'
  END AS issue,
  SUM(tokens_input),
  SUM(tokens_output),
  COUNT(*)
FROM session
WHERE directory LIKE '%switchyard%'
  AND model LIKE '%ornith%'
GROUP BY issue
ORDER BY issue;
"

rows=$(sqlite3 -separator '|' "$DB" "$QUERY")

if (( MARKDOWN )); then
  print "| Issue | Sessions | Input tokens | Output tokens | Total | Hosted equivalent |"
  print "|---|---|---|---|---|---|"
else
  printf "%-8s %9s %14s %13s %14s %12s\n" ISSUE SESSIONS INPUT OUTPUT TOTAL "IF HOSTED"
fi

typeset -i ti=0 to=0 ts=0
while IFS='|' read -r issue tin tout sess; do
  [[ -n "$issue" ]] || continue
  ti+=$tin; to+=$tout; ts+=$sess
  total=$(( tin + tout ))
  cost=$(printf "%.2f" $(( tin / 1000000.0 * IN_RATE + tout / 1000000.0 * OUT_RATE )))
  label=$issue
  [[ "$issue" != "(main)" ]] && label="#$issue"
  if (( MARKDOWN )); then
    printf "| %s | %s | %'d | %'d | %'d | \$%s |\n" "$label" "$sess" "$tin" "$tout" "$total" "$cost"
  else
    printf "%-8s %9s %14s %13s %14s %12s\n" "$label" "$sess" \
      "$(printf "%'d" $tin)" "$(printf "%'d" $tout)" "$(printf "%'d" $total)" "\$$cost"
  fi
done <<< "$rows"

grand=$(( ti + to ))
saved=$(printf "%.2f" $(( ti / 1000000.0 * IN_RATE + to / 1000000.0 * OUT_RATE )))

if (( MARKDOWN )); then
  printf "| **Total** | **%d** | **%'d** | **%'d** | **%'d** | **\$%s** |\n" "$ts" "$ti" "$to" "$grand" "$saved"
  print ""
  print "Actual cost: **\$0.00**. Ornith runs locally in LM Studio; the hosted column is what the"
  print "same traffic would have cost on Sonnet 5 at list price (\$3/MTok in, \$15/MTok out), which is"
  print "the model CLAUDE.md says it replaces."
else
  print ""
  printf "%-8s %9s %14s %13s %14s %12s\n" TOTAL "$ts" \
    "$(printf "%'d" $ti)" "$(printf "%'d" $to)" "$(printf "%'d" $grand)" "\$$saved"
  print ""
  print "Actual cost: \$0.00 — Ornith is local. The last column is what this traffic"
  print "would have cost on Sonnet 5 at list price, the model it replaces here."
fi
